version: '3.8'

services:
  api:
    build: .
    container_name: cosmic_canvas_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4
    container_name: cosmic_canvas_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6-alpine
    container_name: cosmic_canvas_redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
  api:
    